openwisp/openwisp-controller

- openwisp_controller/config/models.py
- requirements.txt
To be merged after django-netjsonconfig 0.6.4 has been released.
> [models] Updated sortedm2m __str__ definition

- README.rst
> Minor change in README

- openwisp_controller/config/templates/admin/login.html
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5100928661192704/
> [admin] Add a link to password reset in login form #19

- .travis.yml
- openwisp_controller/config/controller/urls.py
- openwisp_controller/config/models.py
- openwisp_controller/config/urls.py
- openwisp_controller/config/views.py
- openwisp_controller/geo/api/urls.py
- openwisp_controller/geo/models.py
- openwisp_controller/pki/models.py
- openwisp_controller/pki/urls.py
- tests/settings.py
- tests/urls.py
That's a lot of temporary stuff, I'm fine with fixing it once everything is updated
> [travis] Added django 2.0 to travis tests

- .travis.yml
Ignore eventual pending migrations in other django apps
because otherwise we go mad!
> [qa] Made makemigrations check more specific

- .travis.yml
- openwisp_controller/config/admin.py
- openwisp_controller/config/migrations/0013_last_ip_management_ip_and_status_applied.py
- requirements.txt
Adding support for the new managemetn_ip feature of django-netjsonconfig.
Requires the latest `django-netjsonconfig` version (unreleased, installed from github).
> Management IP

- README.rst
As per the gci task i updated the readme file with the Troubleshoot.
Added common issue while installing GeoDjango.
This will help others that when they encounter issue then what they can do to resolve it or avoid it
> Updated readme file by adding Troubleshoot section to GeoDjango installation

- .travis.yml
Travis failing on master due to an `ImportError` in travis builds.
> [ci] Fix for travis build

- Dockerfile
- README.rst
- docker-compose.yml
- tests/docker-entrypoint.sh
Updated dockerfile to work with pipenv.
Build time on my machine:
no-cache:   ~ 10mins
cache:        ~  1mins
> [docker] Updated docker setup to work with the new version

- .travis.yml
Updated travis.yml to remove warnings and also updated commit name to stop travis from failing
> [controller] Updated travis.yml file

- openwisp_controller/geo/models.py
- openwisp_controller/geo/tests/test_models.py
> [ui] Add location field validation when creating floorplan

- .travis.yml
Added --recursive and --check-only tags.
Fixes #135
> [test] Fix isort issue in travis build #135

- .travis.yml
- openwisp_controller/pki/admin.py
- openwisp_controller/pki/static/pki/js/show_org_field.js
Made organization field visible when importing a CA or Cert.
Fixes #152
> [bug] Organization field is missing when importing a CA or cert. #152

- openwisp_controller/config/admin.py
- openwisp_controller/config/tests/test_controller.py
And change registration disabled test.
> Update hardware id field admin position

- Pipfile
- openwisp_controller/connection/connectors/ssh.py
- openwisp_controller/connection/models.py
- openwisp_controller/connection/tasks.py
- openwisp_controller/connection/tests/base.py
- openwisp_controller/connection/tests/test_admin.py
- openwisp_controller/connection/tests/test_models.py
- openwisp_controller/connection/tests/test_ssh.py
The upload method is necessary to write custom backend that have to upload the configuration on the device and also for the firmware upgrade module.
> [connection] Added upload method + mock-ssh-server tests

- openwisp_controller/connection/models.py
- openwisp_controller/connection/signals.py
- openwisp_controller/connection/tests/test_models.py
> [feature] Emit signal when the value of DeviceConnection.is_working changes

- Pipfile
- README.rst
- docker-compose.yml
* Install python redis library
* Expose Redis port in docker-compose
* Fix apt command with -y argument
Fixes #183
> [docs] Update outdated steps in README instructions #183

- openwisp_controller/connection/tests/base.py
This is required for https://github.com/openwisp/openwisp-firmware-upgrader/issues/26
> [tests] Add _get_credentials method

- openwisp_controller/config/controller/views.py
- openwisp_controller/config/tests/test_controller.py
Multiple devices in one location can be behind the same public IP.
> [device] Allow duplicated last_ip if public IP

- README.rst
- openwisp_controller/connection/models.py
- openwisp_controller/connection/signals.py
- openwisp_controller/connection/tests/test_models.py
Change required for https://github.com/openwisp/openwisp-monitoring/issues/139
> [change] Added 'failure_reason' to is_working_changed signal

- openwisp_controller/config/templates/admin/config/change_form.html
Fixed the problem by updating the script in config/admin
change_form.html
Fixes #173
> [bug] Default templates JS not working for existing devices #173

- openwisp_controller/config/static/config/js/utils.js
- openwisp_controller/config/static/config/js/widget.js
Took advantage to also fix minor style issues in JS code (camel case not being used for function and variable names).
Fixes #225
> [fix] Fixed broken advanced mode in VPN server #225

- .travis.yml
- runtests.py
- tests/pytest.ini
- tests/pytest.sampleapp.ini
> [tests] Run pytest from runtests.py #223

- openwisp_controller/config/static/config/css/admin.css
- openwisp_controller/config/templates/admin/config/change_form.html
Fixed whitespace after overview tab in in device page
> [ui] Fixed whitespace after overview tab in in device page

- CHANGES.rst
- README.rst
- openwisp_controller/geo/utils.py
Closed issue by ensuring API consistency with other modules
and also added documentation for the API
Closes #199
> [api] Device location: improve consistency and document #199

- Dockerfile
- README.rst
- docker-compose.yml
> [docker] note about development docker image

- openwisp_controller/config/static/config/css/lib/jsonschema-ui.css
- openwisp_controller/config/static/config/js/widget.js
- openwisp_controller/config/templates/admin/config/jsonschema-widget.html
- openwisp_controller/config/widgets.py
- openwisp_controller/connection/admin.py
- openwisp_controller/connection/connectors/ssh.py
- openwisp_controller/connection/schema.py
- openwisp_controller/connection/static/connection/css/credentials.css
- openwisp_controller/connection/static/connection/js/credentials.js
- openwisp_controller/connection/tests/test_admin.py
- openwisp_controller/connection/widgets.py
- run-qa-checks
[feature] Added JSON Schema widget to credentials admin
> [feature] Added JSON Schema widget to credentials admin

- openwisp_controller/connection/apps.py
- openwisp_controller/connection/tests/test_models.py
Since now the launch of the task is executed when the transaction is committed to the database, also the check for other updates in progress must be moved there.
This functionality is very delicate because it can't be automatically tested since we use `CELERY_TASK_ALWAYS_EAGER = True` in the test env.
Closes #271.
> [fix] Avoid simultaneous update_config tasks

- openwisp_controller/config/base/base.py
- openwisp_controller/config/tests/test_device.py
- openwisp_controller/config/tests/test_template.py
- openwisp_controller/config/tests/test_vpn.py
> [fix] Fixed CONTEXT setting getting modified at runtime #272

- openwisp_controller/config/admin.py
- openwisp_controller/config/tests/test_admin.py
Fixed issue by adding Template and Vpn to check list
used to build the download_url.
Fixes #259
> [fix] Download configuration button disappeared #259

- .travis.yml
- README.rst
- install-dev.sh
- openwisp_controller/config/apps.py
- openwisp_controller/config/controller/views.py
- openwisp_controller/config/handlers.py
- openwisp_controller/config/signals.py
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/tests/test_notifications.py
- openwisp_controller/geo/channels/routing.py
- openwisp_controller/tests/test_users_integration.py
- requirements-test.txt
- requirements.txt
- tests/openwisp2/settings.py
- tests/openwisp2/urls.py
> [feature] Added notification support from openwisp_notifications

- openwisp_controller/config/base/config.py
- openwisp_controller/config/tests/test_config.py
- openwisp_controller/config/tests/test_template.py
- openwisp_controller/connection/connectors/openwrt/ssh.py
- openwisp_controller/connection/tests/test_models.py
> [fix] Avoid duplicated push updates

- openwisp_controller/config/tests/test_notifications.py
- tests/openwisp2/sample_config/tests.py
@pandafy seems we forgot this.
> [tests] Added TestNotifications to SAMPLE_APP

- openwisp_controller/config/base/template.py
- openwisp_controller/config/tasks.py
- openwisp_controller/config/tests/test_template.py
- openwisp_controller/connection/tasks.py
- tests/openwisp2/sample_config/tests.py
Operations are moved to the background.
Fixes #285.
Some tests are missing, still WIP.
> [fix] Fix timeout when changing template #285

- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/static/config/js/vpn.js
- openwisp_controller/config/tasks.py
- openwisp_controller/config/tests/test_vpn.py
- tests/openwisp2/sample_config/tests.py
> [change] Fix generating DH timeout

- openwisp_controller/config/base/template.py
- openwisp_controller/config/tests/test_template.py
> [fix] Made template config required #276

- openwisp_controller/connection/apps.py
- openwisp_controller/connection/tests/test_notifications.py
- tests/openwisp2/sample_connection/tests.py
> [cleanup] Added connection notification logic #269

- openwisp_controller/config/static/config/js/widget.js
> [fix] Fixed broken variablle validation #311

- openwisp_controller/config/admin.py
Related to https://github.com/openwisp/ansible-openwisp2/issues/216.
> [fix] Removed static() call from admin static files

- openwisp_controller/geo/channels/routing.py
- openwisp_controller/geo/tests/pytest.py
- openwisp_controller/routing.py
- openwisp_controller/urls.py
- tests/openwisp2/routing.py
- tests/openwisp2/settings.py
- tests/openwisp2/urls.py
> [chores] Refactored routing for websockets

- openwisp_controller/config/admin.py
- openwisp_controller/config/static/config/js/widget.js
- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/views.py
> [feature] Added default values to device context #317

- CHANGES.rst
- openwisp_controller/__init__.py
Testing the build and change log for the 0.8.0 release.
Closes #326.
> 0.8.0 release

- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/tests/test_config.py
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/tests/test_device.py
- openwisp_controller/config/tests/test_template.py
- openwisp_controller/config/tests/test_vpn.py
- tests/openwisp2/settings.py
Removed settings specifically set for running tests in settings.py
and mocked then on per test basis.
> [chores] Updated tests bound to development environment

- openwisp_controller/config/static/config/js/utils.js
> [fix] Fixed system context js error #334

- openwisp_controller/config/base/device.py
- openwisp_controller/config/migrations/0029_merge_django_netjsonconfig.py
- tests/openwisp2/sample_config/migrations/0001_initial.py
Made explicit it should either be a hostname or a mac address
> [change] Added help_text to Device.name

- openwisp_controller/config/base/config.py
- openwisp_controller/config/base/template.py
> [chores] Simplified get system context #344

- README.rst
- openwisp_controller/config/admin.py
- openwisp_controller/config/settings.py
- openwisp_controller/config/templates/admin/config/change_form.html
> [change] New setting for config backend #346

- openwisp_controller/geo/utils.py
Removed the deprecated location api url from geo/utils.
Fixes #350
> [fix] Removed deprecated location api url #350

- openwisp_controller/config/static/config/js/utils.js
- openwisp_controller/config/static/config/js/widget.js
> [fix] Fixed default_values override system variables #352

- openwisp_controller/config/admin.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/static/config/js/default_templates.js
- openwisp_controller/config/static/config/js/widget.js
- openwisp_controller/config/templates/admin/config/change_form.html
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/tests/test_views.py
- openwisp_controller/config/utils.py
- openwisp_controller/config/views.py
> [fix] Added backend to default templates filtering #354

- openwisp_controller/config/base/config.py
- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/static/config/css/admin.css
- openwisp_controller/config/static/config/js/tabs.js
- openwisp_controller/config/static/config/js/utils.js
- openwisp_controller/config/templates/admin/config/system_context.html
- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/widgets.py
> [change] Improved system defined variables #344

- openwisp_controller/geo/api/views.py
- openwisp_controller/geo/tests/test_api.py
- openwisp_controller/geo/utils.py
Minor improvements and fixes to the Geo API.
> [change] Changed geojson URL and serializer name for clarity

- openwisp_controller/config/admin.py
- openwisp_controller/config/base/template.py
- openwisp_controller/config/tests/test_admin.py
> [fix] Decoupled admin LogEntry from Template Model #364

- openwisp_controller/config/apps.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/controller/views.py
- openwisp_controller/config/tests/test_config.py
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/utils.py
- requirements.txt
- implemented caching of device checksum view
- cache the query that retrieves the device
- cache the generated checksum
- implemented cache invalidation and update
Closes #396
> [feature] Implemented caching of device checksum view #396

- README.rst
Updated the README with steps that lead to a successful setup.
- Added the steps to setup a virtual env
- Modified "Installing dev dependencies section"
- Added a step to upgrade the pip version to 20.2.4
> [docs] Updated "Installing for development" instructions in the README

- .github/workflows/ci.yml
- openwisp_controller/config/sortedm2m/fields.py
- tests/openwisp2/sample_users/migrations/0001_initial.py
Changed the version of Django to use the exact version in the CI build.
Fixes #417
> [ci] CI fixed for testing on django~=3.0.0 #417

- openwisp_controller/config/controller/views.py
- openwisp_controller/config/tests/test_controller.py
> [fix] Ignored empty values in DeviceUpdateInfoView

- requirements.txt
Fixed in django-x509 0.9.4.
Closes #375
> [fix] Fixed pop up view of CA and cert #375

- openwisp_controller/config/static/config/js/relevant_templates.js
The order of selected templates were not maintained by JavaScript.
Fixes #435
> [fix] Fixed unsaved changes broken due to ordering of templates #435

- openwisp_controller/config/static/config/js/relevant_templates.js
> [fix] Fixed JS bug affecting displaying device templates #447

- README.rst
- openwisp_controller/subnet_division/admin.py
- openwisp_controller/subnet_division/rule_types/base.py
- openwisp_controller/subnet_division/tests/helpers.py
- openwisp_controller/subnet_division/tests/test_admin.py
- openwisp_controller/subnet_division/tests/test_models.py
- requirements.txt
Creates a reserved subnet at the beginning of master subnet
to allow users to provision IPs
Closes #451
> [change] Fixed conflicting provisioned IP address #451 

- openwisp_controller/config/base/config.py
- openwisp_controller/config/static/config/js/relevant_templates.js
- openwisp_controller/config/tests/test_template.py
Required templates are shown as checked to user and before the form
is submitted they are unchecked.
Closes #441
> [chore] Improved required templates JS implementation #441

- openwisp_controller/config/api/urls.py
- openwisp_controller/config/tests/test_api.py
- openwisp_controller/urls.py
- tests/openwisp2/urls.py
> [change] Changed the API URL namespace and endpoints name #467

- openwisp_controller/geo/tests/test_api.py
- openwisp_controller/geo/utils.py
- openwisp_controller/urls.py
- tests/openwisp2/urls.py
Addresses https://github.com/openwisp/openwisp-controller/pull/473#pullrequestreview-668755572
> [change] Renamed API endpoints names and namespace

- openwisp_controller/config/api/views.py
- openwisp_controller/config/tests/test_api.py
> [change] Implemented view permission #454

- openwisp_controller/connection/connectors/openwrt/ssh.py
- openwisp_controller/connection/tests/test_models.py
> [feature] Use SIGUSR1 to update configuration on device #478

- README.rst
- openwisp_controller/geo/utils.py
> [change] Changed API endpoints of geo app #460

- openwisp_controller/config/apps.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/tests/test_config.py
- tests/openwisp2/sample_config/tests.py
> [fix] Invalidate config checksum when VPNClient certificate is renewed #456

- openwisp_controller/config/admin.py
- openwisp_controller/config/tests/test_admin.py
Allows searching for address in Device Admin.
> [feature] Allow searching for address in Device Admin

- openwisp_controller/connection/base/models.py
- openwisp_controller/connection/tasks.py
- openwisp_controller/connection/tests/test_models.py
Used bulk_create instead of individual create query for DeviceConnection.
Closes #479
> [fix] Wrapped credentials auto_add in transaction.on_commit #479

- README.rst
- openwisp_controller/connection/api/serializer.py
- openwisp_controller/connection/api/urls.py
- openwisp_controller/connection/api/views.py
- openwisp_controller/connection/tests/test_api.py
- tests/openwisp2/sample_connection/api/views.py
- tests/openwisp2/sample_connection/tests.py
> [api] REST API for the models of `connection` app #464

- openwisp_controller/config/admin.py
- added group filter in device list
- added description and meta_data to search_fields
> [chores] Admin improvements for groups

- openwisp_controller/config/static/config/js/widget.js
> [fix] JSONSchema Editor maxlength modification handle non-existent schema objects #353

- openwisp_controller/urls.py
- tests/openwisp2/urls.py
> [fix] Included PKI API URLs to `controller.urls` file #511

- openwisp_controller/config/static/config/css/admin.css
- openwisp_controller/config/static/config/css/lib/jsonschema-ui.css
- openwisp_controller/connection/static/connection/css/command-inline.css
- Fixed alignment of help label in configurations.
- Fixed modal of send command.
> [fix] Fixed minor new theme issues

- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/connection/tests/test_admin.py
- openwisp_controller/geo/tests/test_admin.py
- openwisp_controller/pki/tests/test_admin.py
fix broken test in openwisp/openwisp-utils#241.
closes openwisp/openwisp-utils#251
> [test] Update failing tests

- README.rst
- openwisp_controller/geo/api/views.py
- openwisp_controller/geo/tests/test_api.py
> [feature] Added filtering by organization slug in GeoJsonLocationListAPI view #515

- README.rst
- openwisp_controller/subnet_division/base/models.py
- openwisp_controller/subnet_division/rule_types/base.py
- openwisp_controller/subnet_division/rule_types/device.py
- openwisp_controller/subnet_division/rule_types/vpn.py
- openwisp_controller/subnet_division/tasks.py
- openwisp_controller/subnet_division/tests/test_models.py
- openwisp_controller/subnet_division/tests/test_rule.py
> [change] VPN subnet division rule triggers provisioning for existing devices #536

- openwisp_controller/connection/tests/test_notifications.py
Made notification tests to only check changes introduced in
openwisp-controller.
> [fix] Fixed notification tests

- openwisp_controller/subnet_division/base/models.py
- openwisp_controller/subnet_division/static/subnet-division/js/subnet-division.js
- openwisp_controller/subnet_division/tests/test_models.py
Improved test cases for testing subnet division rule validation.
Improvement to #533
Closes #540
> [fix] Added validation for illegal prefixlen in subnet division rule #540

- openwisp_controller/subnet_division/base/models.py
- openwisp_controller/subnet_division/tasks.py
- openwisp_controller/subnet_division/tests/test_models.py
> [fix] Improves SubnetDivisionRule label field validation and update

- README.rst
Changed the chromium install command and
installing jshint instead of jslint
Closes #553
> [update] Development guide #553

- openwisp_controller/config/base/device.py
- openwisp_controller/config/tests/test_device.py
Device and DeviceGroup should belong to the same organization.
> [fix] Added validation for group in device model

- openwisp_controller/config/controller/views.py
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/utils.py
The controller URL pattern used "uuid" converter which does not
allow UUID hex code.
Related to #551
> [fix] Reverted controller view URL pattern #551

- openwisp_controller/connection/apps.py
- requirements.txt
> [deps] Upgraded celery~=5.1.2 #325

- openwisp_controller/config/admin.py
- openwisp_controller/config/templates/admin/config/device_recover_form.html
- openwisp_controller/config/tests/test_selenium.py
- openwisp_controller/config/tests/utils.py
- openwisp_controller/connection/admin.py
- openwisp_controller/connection/base/models.py
- openwisp_controller/connection/static/connection/js/commands.js
- openwisp_controller/connection/tests/test_selenium.py
- openwisp_controller/geo/admin.py
- openwisp_controller/tests/test_selenium.py
- openwisp_controller/tests/utils.py
> [fix] Fixed error on restoring device #577

- CHANGES.rst
- README.rst
- openwisp_controller/config/controller/views.py
- openwisp_controller/config/settings.py
- openwisp_controller/config/tests/test_controller.py
> [fix] Added setting to configure shared management IP address space #578

- openwisp_controller/config/api/views.py
- openwisp_controller/config/tests/test_api.py
- openwisp_controller/connection/api/views.py
- openwisp_controller/connection/tests/test_api.py
- openwisp_controller/geo/api/views.py
- openwisp_controller/geo/tests/test_api.py
- openwisp_controller/mixins.py
- openwisp_controller/pki/api/views.py
- openwisp_controller/pki/tests/test_api.py
- Added tests for Pki API endpoints for bearer authentication
- Added tests for Connection API endpoints for bearer authentication
- Added tests for Config API endpoints for bearer authentication
> [fix] Fixed Geo API endpoints to allow bearer authentication

- openwisp_controller/config/admin.py
- openwisp_controller/config/tests/test_admin.py
> [Fix] Clone template feature does not allow to clone shared templates #594

- README.rst
> [docs] Updated docs for OPENWISP_CONTROLLER_COMMON_NAME_FORMAT #526

- openwisp_controller/config/tasks.py
- openwisp_controller/subnet_division/tasks.py
why we are not using [OpenwispCeleryTask](https://github.com/openwisp/openwisp-utils#openwisp_utilstasksopenwispcelerytask) as a base class for all tasks ? 
Closes #608
> [change] Added time limits to celery tasks #608

- openwisp_controller/config/admin.py
- openwisp_controller/config/tests/test_admin.py
I also found a bug while updating these tests.
> [tests] Fixed tests affected by netjsonconfig updates

- README.rst
- openwisp_controller/config/base/base.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/settings.py
- openwisp_controller/config/tests/test_config.py
- requirements.txt
> [change] Support for instantiating OpenWrt with both 21 and legacy mode #618

- README.rst
Closes #475
Look at the generated result at https://github.com/openwisp/openwisp-controller/tree/issues/475-reorder-readme.
> [docs] Re-ordered and improved README #475

- README.rst
- openwisp_controller/connection/apps.py
- openwisp_controller/connection/base/models.py
- openwisp_controller/connection/settings.py
- openwisp_controller/connection/signals.py
- openwisp_controller/connection/tests/test_models.py
- openwisp_controller/connection/tests/test_notifications.py
Added functionality to ignore "connection not working"
notifications generated due to connectivity issues.
> [fix] Ignore "connection not working" notifications #314

- README.rst
- openwisp_controller/connection/tests/test_ssh.py
- openwisp_controller/geo/api/serializers.py
- openwisp_controller/geo/api/views.py
- openwisp_controller/geo/tests/test_api.py
- openwisp_controller/geo/utils.py
- tests/openwisp2/sample_geo/tests.py
- tests/openwisp2/sample_geo/views.py
> [api] REST API for the models of GEO App #463

- openwisp_controller/config/admin.py
- openwisp_controller/config/api/serializers.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/tests/test_api.py
> [fix] Fixed flaws in enforce_required_templates when changing the organization of a Device #445

- README.rst
- openwisp_controller/config/admin.py
- openwisp_controller/config/apps.py
- openwisp_controller/config/settings.py
- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/tests/test_apps.py
- tests/openwisp2/settings.py
> [feature] Added a pie chart with number of groups #632

- README.rst
- openwisp_controller/config/admin.py
- openwisp_controller/config/static/import_export/import-openwisp.css
- openwisp_controller/config/templates/admin/config/change_list_device.html
- openwisp_controller/config/templates/admin/import_export/import.html
- openwisp_controller/config/tests/test_admin.py
- requirements.txt
- tests/openwisp2/settings.py
> [feature] Added possibility of importing/exporting devices #629

- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/tests/test_vpn.py
> [change] Add VPN subnet CIDR to device system defined variables #642

- openwisp_controller/config/static/config/js/management_ip.js
- openwisp_controller/config/static/config/js/widget.js
- openwisp_controller/config/templates/admin/config/change_form.html
- openwisp_controller/connection/static/connection/js/commands.js
- openwisp_controller/geo/api/views.py
> [Fix] Removed hardcoded static files from js files #660

- CHANGES.rst
(cherry picked from commit 33c92f727f2cbecb0c50e81c26459134875c440b)
> [docs] Added changelog for 1.0.2 release

- README.rst
- openwisp_controller/config/apps.py
- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/handlers.py
- openwisp_controller/config/signals.py
- openwisp_controller/config/tasks.py
- openwisp_controller/config/tests/test_vpn.py
> [Fix] Invalidate checksum cache on VPN server change #667

- openwisp_controller/config/apps.py
- openwisp_controller/config/tests/test_notifications.py
- openwisp_controller/config/utils.py
> [change] Configured target_link for config error notification

- CHANGES.rst
- openwisp_controller/__init__.py
- publiccode.yml
> 1.0.3 release

- CHANGES.rst
(cherry picked from commit eb101a327686c5e1467f089f7536680ef089c27d)
> [docs] Added changelog for 1.0.3 release

- openwisp_controller/config/tests/test_api.py
> [refactor] Fixed flaky test test_devicegroup_list_api #679

- .github/workflows/ci.yml
- openwisp_controller/config/admin.py
Fixes https://github.com/openwisp/openwisp-controller/issues/693
**Blockers**
> [fix] Allow filtering devices by group__isnull=True #693

- openwisp_controller/config/api/serializers.py
- openwisp_controller/config/tests/test_api.py
Fixes #695
**Required by**
- https://github.com/openwisp/openwisp-controller/pull/696
> [fix] Fixed model validation for Device list and detail serializers #695

- openwisp_controller/config/base/template.py
- openwisp_controller/config/controller/views.py
- openwisp_controller/config/tasks.py
These changes make this operation more resilient.
> [change] Increased soft limit of update_template_related_config_status

- openwisp_controller/subnet_division/admin.py
- openwisp_controller/subnet_division/filters.py
- openwisp_controller/subnet_division/tests/test_admin.py
> [feature] Added filter for filtering Subnet by SubnetDivisionRule #588

- openwisp_controller/config/base/config.py
- openwisp_controller/config/tests/test_admin.py
> [fix] Fixed group templates re-creating VPN clients #703

- openwisp_controller/connection/admin.py
- openwisp_controller/connection/static/connection/css/command-inline.css
- openwisp_controller/connection/static/connection/js/commands.js
- openwisp_controller/connection/tests/test_admin.py
> [change:ux] Added command loading overlay #714

- openwisp_controller/pki/tests/test_admin.py
> [chores] Fixed test for Cert.ca foreign key #733

- .gitignore
- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/tests/test_vpn.py
> [fix] Fixed `VpnClient` deletion does not respect `auto_cert` flag #597

- openwisp_controller/config/api/download_views.py
- openwisp_controller/config/api/urls.py
- openwisp_controller/config/api/views.py
- tests/openwisp2/sample_config/api/views.py
Related to: https://github.com/openwisp/openwisp-monitoring/pull/480
> [change] Moved config download api views

- openwisp_controller/config/static/config/css/lib/jsonschema-ui.css
Fixes the following issue:
Result:
> [fix:ui] Fixed inline switcher (VXLAN)

- openwisp_controller/config/static/config/js/widget.js
This workaround allows using variables in IP addresses without destroying the config editor UI when the page loads.
This is meant to be a temporary patch until we find a more elegant and generic solution in future iterations.
> [fix] Workaround for config UI when using variables in addresses

- openwisp_controller/config/tests/test_selenium.py
- openwisp_controller/tests/test_selenium.py
- openwisp_controller/tests/utils.py
We will also need to update [openwisp-monitoring, openwisp-firmware-upgrader and openwisp-network topology ](https://github.com/search?q=org%3Aopenwisp+%22from+openwisp_controller.tests.utils+import+SeleniumTestMixin%22&type=code)
> [chores] Fixed selenium test imports

- openwisp_controller/config/tests/test_selenium.py
- openwisp_controller/tests/test_selenium.py
- requirements-test.txt
> [chores] Use SeleniumTestMixin from openwisp-utils

- openwisp_controller/connection/static/connection/js/commands.js
Closes #772
**Related**
- https://github.com/openwisp/openwisp-notifications/pull/262
> [fix] Increased "timeoutInterval" for ReconnectingWebSocket #772

- .github/workflows/ci.yml
- README.rst
- tests/openwisp2/local_settings.example.py
- tests/openwisp2/settings.py
Related to https://github.com/openwisp/openwisp-utils/pull/351 and https://code.djangoproject.com/ticket/32935.
> [fix] Workaround for spatialite issue on Ubuntu 22.04 LTS

- openwisp_controller/config/static/config/css/admin.css
- openwisp_controller/config/static/config/js/management_ip.js
- Fixed text alignment issue
- Refactored code to use JS conventions
> [chores] Improved editable management IP field

- README.rst
> [docs] Recommended use of ED25519 key #709

- README.rst
- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/tests/test_vpn.py
- requirements.txt
> [feature] Added support for custom ZeroTier interface name

- openwisp_controller/config/admin.py
- openwisp_controller/config/templates/reversion/config/revision_form.html
- openwisp_controller/connection/static/connection/js/commands.js
Fixes https://github.com/openwisp/openwisp-controller/issues/681
**Blockers**
> [fix] Fixed JS of history pages on config app #681 

- openwisp_controller/config/apps.py
- openwisp_controller/config/handlers.py
- openwisp_controller/config/tasks.py
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/tests/test_handlers.py
Controller views return 404 response for disabled organizations.
Closes #815
> [change] Limit actions on disabled organizations #815

- openwisp_controller/config/tests/test_selenium.py
> [fix] Fixed flaky test_create_new_device selenium test #834

- openwisp_controller/config/tasks.py
The default limit on this task was too low.
> [change] Increased limit of change_devices_templates

- README.rst
- openwisp_controller/config/admin.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/base/device.py
- openwisp_controller/config/exportable.py
- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/tests/test_device.py
- openwisp_controller/geo/admin.py
- openwisp_controller/geo/exportable.py
- openwisp_controller/geo/tests/test_admin.py
- requirements.txt
- Added more device, config and geo fields to export
- Fixed UUID bug #850
- Fixed import bug #793 
Fixes #793
Fixes #850
> [change/fix] Improved device export #850

- .github/workflows/ci.yml
> [ci] Fix coveralls build step

- openwisp_controller/config/widgets.py
- openwisp_controller/connection/widgets.py
Avoid manipulating private properties from Django.
> [chores] Cleaned up media property methods

- openwisp_controller/config/base/template.py
- openwisp_controller/config/tests/test_template.py
- openwisp_controller/connection/apps.py
- openwisp_controller/connection/tasks.py
- openwisp_controller/connection/tests/test_models.py
This task can take a long time to run, these changes will help to run it faster.
> [chores] Optimized Template._update_related_config_status

- .github/workflows/ci.yml
> [ci] Run on Ubuntu 24.04 LTS

- .github/workflows/ci.yml
- openwisp_controller/config/tests/test_selenium.py
Temporary workaround for https://github.com/openwisp/openwisp-controller/issues/902.
> [tests] Workaround for beforeunload event

- openwisp_controller/connection/tests/test_api.py
- openwisp_controller/pki/api/serializers.py
- openwisp_controller/pki/tests/test_api.py
Added support for djangorestframework<=3.15.1
> [deps] Added compatibility for djangorestframework<=3.15.1

- openwisp_controller/subnet_division/admin.py
- tests/openwisp2/sample_users/migrations/0001_initial.py
> [chores] Updated the docs URL in SubnetDivisionRuleInlineAdmin #862

- openwisp_controller/config/static/config/js/preview.js
- openwisp_controller/config/tests/test_selenium.py
> [fix] Show PrivateKey in the WireGuard server preview #870

- tests/openwisp2/settings.py
> [chores] Added compatibility with django-allauth~=0.63.6

- .github/workflows/pypi.yml
- requirements-test.txt
- requirements.txt
- Added workflow for PyPI publishing
- Pinned depencies from GitHub to version specifier
> [ci/deps] Added workflow for PyPI publishing and pinned dependencies

- docs/user/settings.rst
- openwisp_controller/config/base/device.py
- openwisp_controller/config/migrations/0001_squashed_0002_config_settings_uuid.py
- openwisp_controller/config/migrations/0013_last_ip_management_ip_and_status_applied.py
- openwisp_controller/config/migrations/0027_add_indexes_on_ip_fields.py
- tests/openwisp2/sample_config/migrations/0001_initial.py
> [chores] Updated help text for device's management IP field

- openwisp_controller/geo/admin.py
- openwisp_controller/tests/test_selenium.py
- requirements.txt
> [fix] Fixed recovering deleted device with related location #936 

- openwisp_controller/config/static/config/css/admin.css
- openwisp_controller/connection/connectors/openwrt/ssh.py
- openwisp_controller/connection/static/connection/css/command-inline.css
- openwisp_controller/connection/tests/test_models.py
Fixes #964
I have performed manual testing with both openwisp-config 1.0.0 and openwisp-config 1.1.0
> [fix] Updated "OpenWrt.update_config" to work with openwisp-config >=.1.0 #964

- openwisp_controller/config/apps.py
- openwisp_controller/config/base/template.py
- openwisp_controller/config/tests/test_admin.py
> [fix] Fixed reverting template doesn't send config_changed signal #836

- requirements.txt
> [chores] Fixed the respository URL for django-loci

- openwisp_controller/connection/api/urls.py
- openwisp_controller/connection/api/views.py
- openwisp_controller/connection/apps.py
- openwisp_controller/connection/tasks.py
The URL params appear in the API docs and in the unified docs too, but the format used was different and inconsistent.
> [chores] Changed device_pk to device_id for consistency with docs

- openwisp_controller/config/base/config.py
- openwisp_controller/config/tests/test_api.py
- openwisp_controller/config/tests/test_config.py
- openwisp_controller/config/tests/test_vpn.py
Backporting the solution for #832 to the 1.1 version.
> [fix:1.1] Do not allow applying more than 1 templates of same VPN server #832

- openwisp_controller/config/tests/test_vpn.py
> [fix:tests] Updated test_zerotier_vpn_client_template #832

- CHANGES.rst
- README.rst
- openwisp_controller/__init__.py
- openwisp_controller/config/admin.py
- openwisp_controller/config/apps.py
- openwisp_controller/config/base/base.py
- openwisp_controller/config/base/config.py
- openwisp_controller/config/base/vpn.py
- openwisp_controller/config/controller/views.py
- openwisp_controller/config/handlers.py
- openwisp_controller/config/tasks.py
- openwisp_controller/config/tests/test_admin.py
- openwisp_controller/config/tests/test_config.py
- openwisp_controller/config/tests/test_controller.py
- openwisp_controller/config/tests/test_handlers.py
- openwisp_controller/config/tests/test_vpn.py
- openwisp_controller/config/tests/utils.py
- openwisp_controller/config/utils.py
- openwisp_controller/geo/tests/test_api.py
- openwisp_controller/geo/tests/utils.py
- openwisp_controller/geo/utils.py
- requirements-test.txt
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
--- 
All commits in the master branch since 1.1.1 tag: https://github.com/openwisp/openwisp-controller/compare/1.1.1...master
Commits included for the 1.1.2 release: https://github.com/openwisp/openwisp-controller/compare/1.1.1...release-1.1.2
> 1.1.2 release

- docs/user/shell-commands.rst
> [docs] Fixed reference in the shell commands docs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/workflows/ci.yml
- .github/workflows/pypi.yml
- openwisp_controller/config/fixtures/test_templates.json
- openwisp_controller/config/static/config/css/admin.css
- openwisp_controller/config/static/config/css/lib/advanced-mode.css
- openwisp_controller/config/static/config/css/lib/jsonschema-ui.css
- openwisp_controller/config/static/config/js/preview.js
- openwisp_controller/config/static/config/js/relevant_templates.js
- openwisp_controller/config/static/config/js/switcher.js
- openwisp_controller/config/static/config/js/utils.js
- openwisp_controller/config/static/config/js/widget.js
- openwisp_controller/connection/static/connection/css/command-inline.css
- openwisp_controller/connection/static/connection/js/commands.js
- openwisp_controller/subnet_division/static/subnet-division/js/subnet-division.js
- openwisp_controller/tests/mixins.py
- publiccode.yml
- tests/openwisp2/sample_config/fixtures/test_templates.json
> [qa] Formatted JS, YAML and markdown

- .github/workflows/ci.yml
- docs/developer/installation.rst
- runtests
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
> [tests] Moved test logic to dedicated script

- openwisp_controller/config/migrations/0061_config_checksum_db.py
Bug:
Config.update_status_if_checksum_changed() sets the Config.status
to modified if the Config.checksum_db field is empty. In the migration
Config.checksum_db is empty, thus all Config.status is set to modified
to all devices.
Fix:
Use Config.objects.bulk_update() to populate the Config.checksum_db field.
It does not call save(), nor it sends pre_save and post_save signals.
Thus, it avoids any side-effects from the migration.
> [fix] Populate Config.checksum_db field without modifying Config.status
