openwisp/openwisp-controller

README.rst
`libsqlite3-mod-spatialite` is required on Debian Stretch.
=> [docs] Update dependencies

.travis.yml, openwisp_controller/config/models.py, openwisp_controller/config/tests/test_template.py
This code effectively, overrides the save() function of Cert to check for a corresponding device every time a Certificate is created and then checks for the organization of that device and updates the cert object accordingly and saves it.
=> [x509] Fix certificates without organization assigned #34 

.travis.yml
Please correct me if i am wrong, but changing lock file during travis runs is not useful, right?
=> [travis] skip-lock during installation

openwisp_controller/config/migrations/0016_default_organization_config_settings.py
This code creates default `OrganizationConfigSettings` for each organization which dosen't have it. This action is triggered whenever migrations are run.  
Fixes #39
=> [organization] Create default organization settings #39

README.rst
In `README.rst` there were invisible non-ascii characters which make the install fail on systems where an appropriate locale (`de_DE.utf8` for example) is not installed:
> pip3 install -U https://github.com/openwisp/openwisp-controller/tarball/master
Collecting https://github.com/openwisp/openwisp-controller/tarball/master
Downloading https://github.com/openwisp/openwisp-controller/tarball/master
/ 286kB 964kB/s
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-gskv33m3-build/setup.py", line 28, in <module>
long_description=open('README.rst').read(),
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec …
=> [docs] Remove invisible non-ascii characters

openwisp_controller/config/models.py, openwisp_controller/config/tests/test_device.py
In the config class, device.organization was assigned to organization
without checking if the device actually had the organization or not.
Performing this check before assignment fixed the issue.
Fixes #24
=> [config/models] Fixed Error saving Device without organization #24

openwisp_controller/config/models.py
The hardware_id should be used as the string representation for a device if the hardware_id feature is enabled.
=> [models] Use hardware_id as string representation if that feature is enabled

.travis.yml, README.rst, setup.py
- 3.4 support is dropped by Twisted and it no more works -- hence moved to Python3.5.
- travia's default container is now xenial, hence trusty is mentioned explicitly.
=> [chores] python3.5 or higher + travis fix

.travis.yml, tests/openwisp2/settings.py
Added support for newer versions of ubuntu.
Fixes https://github.com/openwisp/openwisp-controller/issues/119
=> [Travis] Added support for newer versions of Ubuntu

Pipfile
The coveralls package already has a dependency on coverage
and sets the boundary according to its support for the coverage library.
We should not duplicate this information.
=> [ci] Implicitly get coverage version from coveralls

openwisp_controller/config/migrations/0001_squashed_0002_config_settings_uuid.py, openwisp_controller/config/models.py, setup.py
Removed the logics which were duplicated
in the others modules and redefined it here to enable reusability and ease debugging.
Related to openwisp/openwisp-utils#40
=> [django] Generalize uuid/key/receive_url logic

docker-compose.yml, tests/openwisp2/settings.py
Added a variable in docker-compose.yml to pass redis url. If no variable is passed it will pick up the default value which is set in settings.py.
=> Wrong Redis url passed to django.

openwisp_controller/connection/models.py, openwisp_controller/connection/tests/test_models.py
Don't add credentials to devices that don't have a config yet
but create the Credential anyways.
Fixes #172
=> [bug] Auto add device credential can fail #172

openwisp_controller/connection/models.py, openwisp_controller/connection/tests/test_models.py
An exception occurred before validation of the fields.
Fixes #180
=> [validation] Capture exception when adding device credential without type #180

README.rst, openwisp_controller/connection/models.py, openwisp_controller/connection/signals.py, openwisp_controller/connection/tests/test_models.py
Follow up to PR #179 
I found that custom signals don't provide object **instance** triggering them by default but it would be required in openwisp_monitoring#4, so added the same.
=> [models] Added instance triggering is_working_changed signal

requirements.txt
Pin celery to 4.4.2.
Related to https://github.com/openwisp/openwisp-firmware-upgrader/issues/78
=> [deps] Pin celery to 4.4.2

.jslintrc, openwisp_controller/config/admin.py, openwisp_controller/config/static/config/css/admin.css, openwisp_controller/config/static/config/js/vpn.js, run-qa-checks
After 2.5 seconds a text which asks the user to wait is shown.
We need this because generating the Diffie Helman of 2048 bits
length takes considerable more time.
Closes #227
=> [chores] UX: added loading indicator when VPN server is created #227

openwisp_controller/config/migrations/0032_update_legacy_vpn_backend.py
1. Tested with upgrading a vpn created from version 0.7.0post1
2. Sorry I missed this bug, it's second in the same PR! :sweat: 
Closes #234
=> [fix] add missing legacy vpn backend migration #234

openwisp_controller/config/apps.py, openwisp_controller/config/base/config.py, openwisp_controller/config/tests/test_controller.py, openwisp_controller/config/tests/test_template.py
If SSH push is configured, `config_modified` triggers an attempt to connect to the device, which will fail when a device has just registered.
=> [fix] Avoid triggering config_modified during registration

openwisp_controller/pki/apps.py, tests/openwisp2/settings.py
Let's keep things simple for our users.
The pki models are the default ones, there's no need to require users to set the setting explicitly.
This also simplifies things in ansible-openwisp2, docker-openwisp,
openwisp-monitoring and openwisp-firmware-upgrader, since we won't
have to update the settings of those projects, things will just keep working normally.
I think this is the approach to follow whenever a new setting is added,
we should provide a default value and avoid having the user to define it
explicitly.
=> [change] Avoid need of DJANGO_X509_CA_MODEL, DJANGO_X509_CERT_MODEL

openwisp_controller/config/migrations/0001_squashed_0002_config_settings_uuid.py, openwisp_controller/config/migrations/0003_template_tags.py, openwisp_controller/config/migrations/0004_add_device_model.py, openwisp_controller/config/migrations/0005_populate_device.py, openwisp_controller/config/migrations/0013_last_ip_management_ip_and_status_applied.py, openwisp_controller/config/migrations/0018_config_context.py, openwisp_controller/config/migrations/0023_update_context.py, openwisp_controller/config/migrations/0027_add_indexes_on_ip_fields.py, openwisp_controller/config/migrations/0028_template_default_values.py, openwisp_controller/config/migrations/0029_merge_django_netjsonconfig.py, openwisp_controller/config/migrations/__init__.py, openwisp_controller/connection/migrations/0001_initial.py, openwisp_controller/connection/migrations/0002_credentials_auto_add.py, openwisp_controller/geo/migrations/0001_initial.py, setup.cfg, tests/openwisp2/sample_config/migrations/0001_initial.py, tests/openwisp2/sample_config/migrations/0002_default_groups_permissions.py, tests/openwisp2/sample_connection/migrations/0001_initial.py, tests/openwisp2/sample_geo/migrations/0001_initial.py
=> [migrations] Flake8 migration + swapper fix #263

openwisp_controller/config/base/config.py, openwisp_controller/config/base/template.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_template.py
Config.context and Template.default_values must always be a dictionary.
Falsy values will be converted to empty dictionary automatically.
=> [fix] Validate Config.context and Template.default_values

README.rst
Added a separate row for units for following:
1. `OPENWISP_SSH_AUTH_TIMEOUT`
2. `OPENWISP_SSH_BANNER_TIMEOUT`
3. `OPENWISP_SSH_COMMAND_TIMEOUT`
4. `OPENWISP_SSH_CONNECTION_TIMEOUT`
in the README.rst
Fixes #278
=> [docs] Added units for timeout settings in README #278

openwisp_controller/config/base/device.py, openwisp_controller/connection/settings.py, openwisp_controller/connection/tasks.py
This allows openwisp-monitoring to override the can_be_updated
method to take into account the monitoring status, so that
push updates won't be attempted
Related to #291
=> [feature] Allow using a different device model in update_config #291

openwisp_controller/connection/base/models.py, openwisp_controller/connection/migrations/0005_device_connection_failure_reason.py, tests/openwisp2/sample_connection/migrations/0001_initial.py
Changed "openwisp_controller.connection.base.models.DeviceConnection" to
"TextField" from "CharField" with limited size.
This mitigates long failed_reason ending up in "django.db.utils.DataError"
error.
Fixes #298
=> [enhancement] Changed "DeviceConnection.failure_reason" field to TextField #298

openwisp_controller/connection/apps.py, openwisp_controller/connection/tests/test_notifications.py
- notifications should not be generated when is_working is None (new device)
- tests were not running because were not inheriting TestCase, hence the code was not properly ported
Related to #269
=> [fix] Fixed regression in connection notifications #269

CHANGES.rst, README.rst, openwisp_controller/config/admin.py, openwisp_controller/config/tests/test_views.py, openwisp_controller/config/urls.py, openwisp_controller/config/widgets.py, openwisp_controller/urls.py, tests/openwisp2/urls.py
Current solution:
- Moved schema.json to a seperate url file in openwisp-controller and register it in the main urls file with `include()`. The problem with this approach is that it changes namespace of schema to `config_admin` from `admin`.
Other possible solutions:
1. Monkey-patch `OpenWISPAdminSite` (Avoiding)
2. Override `OpenWISPAdminSite` (Avoiding)
3. Register a hidden Adminclass, which includes the url.
Looking for best possible solution... 
Closes #304
=> [urls] Moved schema.json url to common path

CHANGES.rst, openwisp_controller/__init__.py, publiccode.yml
I am sceptical whether these changes are worth adding to changelog
```
- Changed the `preview` button colors for better readability
- Added *help text* for *device name* field
```
Changelog is written from [this compare](https://github.com/openwisp/openwisp-controller/compare/0.8.0...master).
--------------
Closes #341
=> 0.8.2 release

README.rst
Using openwisp2 Ansible role does not require to manually configure
push updates.
=> [docs] Updated docs for deafult access credentials

openwisp_controller/connection/connectors/ssh.py, openwisp_controller/connection/tests/test_ssh.py
Fixes #370
Another issue related to `openwisp-firmware-upgrader` is that `/sbin/sysupgrade` calls `ubus call system sysupgrade` in the end, which can exit with != 0 even if the sysupgrade is successful (for me a successful sysupgrade returns -1).
=> [fix] Connection: Improve logging and unicode conversion #370

openwisp_controller/config/tests/test_vpn.py, openwisp_controller/vpn_backends.py
If the config misses the "openvpn" key, validation must fail, because it is surely a mistake.
=> [fix] Hardened config validation of OpenVpn backend

README.rst, openwisp_controller/geo/api/views.py, openwisp_controller/geo/tests/test_api.py, openwisp_controller/geo/utils.py, requirements.txt, tests/openwisp2/sample_geo/views.py
=> [feature] Add geojson endpoints #360

.github/workflows/ci.yml, requirements.txt
Edited the files that supported Django 2.2 , removed its support and upgraded the version to Django 3.0
Fixes #297
=> [deps] Drop support for Django 2.2 #297

openwisp_controller/config/static/config/js/widget.js
This change to the jsonschema-widget JS allows the widget to work also when there's only one schema to use.
=> [fix] Allow jsonschema widget to work with a single schema

README.rst, openwisp_controller/config/base/config.py, openwisp_controller/config/base/template.py, openwisp_controller/config/signals.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_template.py, tests/openwisp2/settings.py
- the signal is now always emitted on templates changes m2m events,
also if config.status is modified, with the differences that
only post_add and post_remove m2m events are used, while
post_clear is ignored, which fixes the duplicate signal emission
caused by the implementation of sortedm2m;
i made sure to document these details in the README
- added action and previous_status arguments, which allow to
understand where the config_modified signal is being emitted from,
this allows more advanced usage of the signal by custom implementations
Closes #394
=> [change] Reworked config_modified signal implementation

openwisp_controller/config/base/template.py, openwisp_controller/config/tests/test_template.py
The config related to a template were not being flagged for update
when default_values were changed.
Moreover, during debugging, I found out that in some cases
the action was being performed even if there were no real changes,
the only difference being the new value was an instance of dict
while the value loaded from the model is an instance of OrderedDict.
This change fixes both issues.
=> [fix] Update related config when template default_values are changed

openwisp_controller/config/base/config.py, openwisp_controller/config/base/device.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_device.py
[change] Perform checks for changed name or config during save()
Perform checks to know whether the device name has been changed
or the configuration details have changed during save() rather
than clean(), because clean() may be called multiple times
before save() and we want to execute these operations only once.
=> [change] Move changes check to save methods

openwisp_controller/config/static/config/js/unsaved_changes.js, openwisp_controller/config/static/config/js/widget.js
Location geometry was not being parsed from JSON and hence
the geometry JSON representation had some slight differences
which where triggering the unsaved changes alert.
I took advantage to simplify the code and to fix the
non camelcase functions and variables in this part of the code.
I also updated a global variable name strating with _njc
(netjsonconfig) to owc (openwisp-controller).
Fixes #388
=> [fix] Fixed unsaved_changes.js when location is present #388

openwisp_controller/geo/api/serializers.py, openwisp_controller/geo/api/views.py
- Moved the serializer classes from the `views.py` file to a separate `serializers.py` file.
closes #414
=> [change] Separated the serializer classes from views #414

openwisp_controller/config/admin.py, openwisp_controller/config/static/config/js/default_templates.js, openwisp_controller/config/templates/admin/config/change_form.html, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_views.py, openwisp_controller/config/views.py
Optimized fetching default templates using URL schema. 
A non-superuser can only request default templates for organizations it manages
Closes #420
=> [fix] Fixed authorization bug in get_default_templates view #420

openwisp_controller/config/static/config/js/default_templates.js, openwisp_controller/config/static/config/js/widget.js
The JS code made multiple HTTP request for fetching default template
values when any of organization or backend field were updated.
Fixed it not triggering "click" event of sortedm2m-items and manaully
updating primary keys of templates using JS.
Closes #423
=> [fix] Fixed multiple requests made for fetching default template values #423

README.rst
=> [docs] Fixed the typo of Geo App API Endpoint #430

openwisp_controller/connection/apps.py, openwisp_controller/connection/tests/test_notifications.py, tests/openwisp2/sample_connection/tests.py
Invalidating cache using "openwisp_notification.handlers.register_notification_cache_update"
before creating notification fixed the issue. The notification module was using connection object from the cache
and not from the database.
Closes #415
=> [fix] Fixed outdated failure reason for connection working notification #415

openwisp_controller/config/static/config/js/widget.js
The issue arose because the JSON Schema library uses selec2('enable') for
enabling or disabling select2 fields. According to the "Migrating from 3.5" section
in select2 documentation, select2('enable') has been deprecated.
The solution is to override the methods using it to simply modify
select2.disabled property.
Closes #505
=> [fix] Fixed JSONSchema editor select2 fields getting disabled #505

openwisp_controller/config/static/config/js/widget.js
Bugs fixed:
- Executing a command, would raise a 'Invalid JSON' alert in the
advance mode of the configuration even if the JSON is valid
- The device page deals with two schema and the container for
advance mode editor used 'id="advanced_editor"'. Fetching the advance
mode editor using the 'id' always returned the first occurence
(advance mode editor of configuration). This used to create multiple
advance mode editor DOM elements inside the container all of which
had their own event listeners. Hence, full screen toggling was not
working properly.
Closes #506
=> [fix] Fixed advanced editor quirks #506

openwisp_controller/config/base/device.py, openwisp_controller/config/migrations/0036_device_group.py, tests/openwisp2/sample_config/migrations/0001_initial.py
@pandafy let's ensure verbose names are always lowercase (they get converted to have the first letter uppercase if needed), unless the labels are acronyms.
=> [chores] Ensure Device.group.verbose_name is lowercase for consistency

openwisp_controller/connection/connectors/ssh.py, openwisp_controller/connection/tests/test_ssh.py
If a command with suppressed output failed, CommandFailedException
would be raised with an emptry string as argument, which makes
debugging issues really hard.
In this cases we shall instantiate the exception with the same
message passed to the log.
I found out these assertions were not being called while working
on the previous commit.
PS: found this while debugging https://github.com/openwisp/openwisp-firmware-upgrader/issues/151.
=> [fix] Fix failed command suppressed output + fixed a few tests in TestSsh

openwisp_controller/config/apps.py, openwisp_controller/config/tests/test_admin.py, openwisp_controller/connection/apps.py, openwisp_controller/connection/tests/test_admin.py
Moved group registration and its test code to the connection app. And the device(including tests) is still being registered in the config app.
close #512
=> [fix] Registered menu group in connection app #512

README.rst, openwisp_controller/subnet_division/admin.py, openwisp_controller/subnet_division/base/models.py, openwisp_controller/subnet_division/static/subnet-division/css/subnet-division.css, openwisp_controller/subnet_division/static/subnet-division/js/subnet-division.js, openwisp_controller/subnet_division/tests/test_models.py, run-qa-checks
Validation:
- Size of provisioned subnets cannot be changed
- Number of provisioned subnets cannot be changed
- Number of provisioned IP can only be increased
UX:
- If a subnet is not shared, organization fields of related
Subnet Divsion Rule will be hidden and automatically set
to organization of the subnet.
Closes #520
=> [enhancement] Improved validation of subnet division rules #520

.github/workflows/ci.yml, openwisp_controller/connection/tests/test_api.py, openwisp_controller/pki/tests/test_api.py, requirements-test.txt, tests/openwisp2/sample_users/tests.py
- Minor changes to CI configuration to ensure correct version
of Django in the Python environment.
=> [chores] Fixed tests for sample_users

.github/workflows/ci.yml
Add python version 3.8 and 3.9 to github action ci tests. Remove python 3.7.
Fixes #561
=> [ci] Add new python runtime #561

openwisp_controller/config/admin.py, openwisp_controller/config/tests/pytest.py, openwisp_controller/config/tests/test_admin.py, openwisp_controller/connection/api/urls.py, openwisp_controller/connection/channels/routing.py
The ConfigAdmin download URL pattern used "uuid" converter
which does not allow UUID hex code.
Improvement to #583
=> [fix] Fixed configuration download URLs #583

openwisp_controller/config/admin.py, openwisp_controller/connection/admin.py, openwisp_controller/connection/base/models.py, openwisp_controller/connection/tests/test_api.py, openwisp_controller/geo/admin.py
DeviceAdmin is used by other modules that register InlineModelAdmin
using monkey patching. The default implementation of reversion.register
ignore such inlines and does not update the "follow" field accordingly.
Thus, a classmethod is added in  DeviceAdmin to update the
"follow" fields of the Device model. This is achieved by unregistering
the Device model from reversion and re-registering it with updated
"follow" fields without altering other options.
Related to #577
=> [change] Made updating Device reversion follow updatable #577

openwisp_controller/geo/api/views.py, openwisp_controller/geo/tests/test_api.py
Checks for presence of key attribute first, because in the browsable UI this method is getting passed also Location instances, which do not have the key attribute.
=> [fix] Fixed bug in device location API browsable UI page

README.rst
We don't need snap to install chromium, apt has this package as well.
=> [docs] Removed snap install from docs

openwisp_controller/connection/connectors/ssh.py, openwisp_controller/connection/tests/test_ssh.py
We don't need to log in the application because the output is shown to the user anyway.
=> [change] Updated log levels for connection.connectors.ssh

.github/workflows/ci.yml, openwisp_controller/connection/connectors/ssh.py, openwisp_controller/connection/tests/test_ssh.py
Paramiko versions > 2.8 try to use sha2 as a default
HostKeyAlgorithms if the target SSH server doesn't
advertise the preferred HostKeyAlgorithms, which
is the case for OpenWrt <= 19.
This causes SSH connections to fail with:
"Pubkey auth attempt with unknown algo",
because dropbear on OpenWrt <= 19 doesn't
support sha2.
The fix suggested by Paramiko is to disable
the sha2 HostKeyAlgorithms,
which is not great for systems where newer versions of
OpenWrt and dropbear are in use, for this reason, this
patch disables the sha2 HostKeyAlgorithms only if a first
SSH connection attempt fails by raising the exception
paramiko.ssh_exception.AuthenticationException.
As a bonus fix, I found out that it's better
to explicitly close the SSH connection when the authentication
fails, otherwise a …
=> [fix] SSH Connection: fixed OpenWrt >= 19 authentication failure #643

openwisp_controller/config/base/device.py, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_device.py
Creating a new device object from the admin dashboard
emitted "device_group_changed" and "device_name_changed"
signals. The code for checking the values of changed fields
didn't take creating a device from admin into consideration.
Fixed the code that checks changed fields and added an
automated test for the same.
Closes #649
=> [fix] Fixed changed signals emitting on the creation of new device #649

openwisp_controller/config/admin.py, openwisp_controller/pki/admin.py, openwisp_controller/pki/base/__init__.py, openwisp_controller/pki/templates/pki/change_list.html, openwisp_controller/tests/utils.py
For some obscure reasons the django-reversion button
was not being shown to operators.
I concluded this was not done on purpose and proceeded
to remove the bogus code.
@atb00ker I have no idea how this code ended up here in GSOC20 lol.
=> [fix] Show reversion button to operators too

openwisp_controller/config/api/serializers.py, openwisp_controller/config/tests/test_api.py
=> [Fix] Save config updated details in device update API #658

README.rst
The docs suggested to include URLs for IPAM and notifications
module in the root "urls.py" but these URL patterns are already
included by "openwisp_controller.urls".
=> [docs] Fixed documentation for root URL patterns

CHANGES.rst, openwisp_controller/__init__.py
-   Fixed [device's "changed" signals emitting on the creation of new
device][]
-   Fixed *django-reversion's* recovery buttons were hidden from users
of the "Operator" group in the admin dashboard of `Certificate` and
`CA` models
-   Removed [hardcoded static URLs][] which created issues when static
files are served using an external service (e.g. S3 storage buckets)
-   Fixed [permissions for "Operator" and "Administrator" groups to
access "OrganizationConfigSettings" objects][]
-   Fixed [support for multiple wireguard tunnels on the same devices][]
-   Fixed ["/api/v1/controller/device/{id}/" REST API endpoint not
updating the device's configuration backend][]
[device's "changed" signals emitting on the creation of new device]: …
=> 1.0.2 release

openwisp_controller/config/tests/test_notifications.py, openwisp_controller/connection/tests/test_notifications.py
Bug:
In openwisp-notification 1.0.2, the operation for creating notification
settings when an organization is created is wrapped in transaction.on_commit.
Tests which relied on this functionality and which inherited from
TestCase class were failing.
Fix:
Moved these tests to test class which inherits from TransactionTestCase.
=> [fix] Fixed tests failing due to openwisp-notification 1.0.2

openwisp_controller/connection/connectors/ssh.py, openwisp_controller/connection/tests/test_ssh.py
SSH servers don't like it when sessions aren't closed by clients...
=> [fix] Close ssh session before opening a new one

openwisp_controller/pki/tests/test_admin.py
The test was checking for a string that can be present in UUID of objects. Hence, it failed unexpectedly at times.
Fixes #465
=> [fix] Fixed flaky test_ca_queryset #465

openwisp_controller/config/base/vpn.py, openwisp_controller/config/static/config/js/vpn.js, openwisp_controller/config/tests/test_vpn.py, openwisp_controller/subnet_division/tests/helpers.py, openwisp_controller/subnet_division/tests/test_models.py
VPN server with OpenVPN backend can be assigned a subnet and an IP address. VpnClients created for such VPN server can also utilise subnet division rule functionality.
Closes #707
=> [change] Allowed defining subnet and IP address for VPN with OpenVPN backend #707

openwisp_controller/subnet_division/admin.py
I came up with this while reviewing https://github.com/openwisp/openwisp-controller/pull/716.
=> [change:ux] Show related_device before created/modified in subnet list

openwisp_controller/config/base/config.py
The previous fix to #703 will make a database query for every old_template. This patch provides a more optimized solution.
Related to #723
=> [fix] Fixed group templates re-creating VPN clients #723

.coveragerc, .github/workflows/ci.yml, README.rst, docker-compose.yml, openwisp_controller/subnet_division/rule_types/base.py, openwisp_controller/subnet_division/tests/test_rule.py, requirements-test.txt, runtests.py, tests/openwisp2/postgresql_settings.py
BaseSubnetDivisionRuleType.get_max_subnet will order queryset using
the "subnet" field when PostgreSQL database backend is used. Otherwise,
it will fallback to using "created" field for ordering.
Closes https://github.com/openwisp/openwisp-controller/issues/728
=> [fix] Use BaseSubnetDivisionRuleType.get_max_subnet order by subnet #728

.gitignore
- When running coverage testing, it creates `.coverage.*` files, this change will exclude them from git.
=> [chores] Added `.coverage.*` files to `.gitignore`

openwisp_controller/config/static/config/js/preview.js
Systemwide shared objects are identified with a **"null"** id in the backend. When submitting a preview form, Django will raise an validation error if the form field corresponding to the object ID is not empty or does not contain a valid `UUID` string.
Fixes #742
=> [fix] Fixed broken shared template preview #742

openwisp_controller/config/static/config/js/widget.js, openwisp_controller/config/widgets.py
- Allowed to define extra CSS classes in the JSONSchema widget
- widget.js will not instantiate editor for fields with "manual" CSS class
=> [enhancement] Improved JSONSChema editor widget

Dockerfile
I noticed that the containers only start properly if the python version is set to 3.9.
=> [chores] Update python in dockerfile to 3.9

openwisp_controller/config/api/serializers.py, openwisp_controller/config/tests/test_api.py
=> [fix] Fixed REST API can creates device configs inadvertently #699

openwisp_controller/connection/api/views.py, openwisp_controller/connection/tests/test_api.py
- Command APIs inherits "ProtectedAPIMixin" for consistency with other API endpoints
- If an organization admin tries to access commands for a device of another organization, then the API would return 404 response. Earlier, the API returned 200 reponse with an empty list.
Fixes #754
=> [fix] Fixed command APIs permissions #754

openwisp_controller/config/base/config.py, openwisp_controller/config/base/template.py, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_template.py, openwisp_controller/connection/tests/test_models.py
The status of related Config objects will only be updated if the checksum of template's configuration changes.
Closes #213
=> [fix] Fixed updating template puts devices in perennial "modified" state #213

openwisp_controller/subnet_division/rule_types/vpn.py, openwisp_controller/subnet_division/tests/test_models.py
Bug:
When a device has more than 1 Vpn templates applied, then removing any one of the template deletes provisioned subnets for both VpnClients.
Fix:
Only delete the related provisioned subnets when VpnClient is deleted.
=> [fix] Fixed deletion of VpnClient deleted all provisioned subnets

openwisp_controller/config/controller/views.py, openwisp_controller/config/tests/test_controller.py
- test_register_with_org_id: the test was passing without any change
- test_register_with_org_param: trying to pass the org ID in the "organization" parameter caused an uncaught exception, the change in the code fixes the error
=> [tests/fix] Test passing arbitrary org params to register view

openwisp_controller/config/admin.py, openwisp_controller/config/tests/test_admin.py
Bug:
It was not possible to change the ordering of the applied templates from the device's change page.
=> [fix] Fixed re-ordering applied templates in device config

openwisp_controller/config/sortedm2m/fields.py, openwisp_controller/config/sortedm2m/forms.py, openwisp_controller/config/static/sortedm2m/patch_sortedm2m.js
=> [fix] Fixed re-ordering templates on device add page #434

openwisp_controller/config/base/config.py, openwisp_controller/config/base/vpn.py, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_vpn.py, openwisp_controller/pki/tests/test_api.py
Removing VPN template from a device will not delete related Cert object. Instead, it will mark the certificate as revoked.
Closes #827
=> [feature] Removing VPN template will not delete related Cert #827

openwisp_controller/connection/base/models.py, openwisp_controller/connection/tests/test_models.py
DeviceConnection.update_config used to report the config as applied automatically, but this can potentially lead to inconsistencies. The config applied status is reported by the openwisp agent once the config has been applied successfully.
=> [change] DeviceConnection.update_config will not flag as applied

openwisp_controller/connection/admin.py, openwisp_controller/connection/tests/test_admin.py
Add WritableCommandInline to the DeviceAdmin only when the user has change permission for Command model.
=> [fix] Add WritableCommandInline when user has change permission

openwisp_controller/config/static/config/js/unsaved_changes.js
=> [fix] Unsaved changes alert disable on preview view

openwisp_controller/subnet_division/base/models.py, openwisp_controller/subnet_division/rule_types/base.py, openwisp_controller/subnet_division/tests/test_models.py
Supersedes https://github.com/openwisp/openwisp-controller/pull/859.
Fixes #842
@pandafy @praptisharma28 please review.
=> [fix] Dealt with small subnets #842

openwisp_controller/config/static/config/css/lib/jsonschema-ui.css, openwisp_controller/config/static/config/js/vpn.js, openwisp_controller/config/tests/pytest.py, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_api.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_controller.py, openwisp_controller/config/tests/test_device.py, openwisp_controller/config/tests/test_device_group.py, openwisp_controller/config/tests/test_notifications.py, openwisp_controller/config/tests/test_selenium.py, openwisp_controller/config/tests/test_template.py, openwisp_controller/config/tests/test_views.py, openwisp_controller/config/tests/test_vpn.py, openwisp_controller/config/tests/utils.py, openwisp_controller/geo/tests/test_api.py, tests/openwisp2/settings.py
Due to changes in the Django admin HTML, the form rows weren't hidden as expected.
This patch should fix the issue and also be more robust to future Django upgrades.
Added a selenium test.
=> [fix:ui] Fixed UI switcher in VPN server admin

openwisp_controller/config/api/filters.py, openwisp_controller/config/tests/test_api.py
Allow searching by name and/or mac address (case insensitive) in the device API list endpoint.
=> [feature] API: added name and mac_address to device list filters

openwisp_controller/config/tasks.py, openwisp_controller/subnet_division/tasks.py
We should not use OpenwispCeleryTask class on celery tasks that queries over several objects in the database.
=> [fix] Fixed celery tasks timeouts

.github/workflows/ci.yml, openwisp_controller/config/admin.py, openwisp_controller/config/tests/test_admin.py
=> [fix] Admin actions require model permissions

.github/workflows/ci.yml, openwisp_controller/subnet_division/rule_types/base.py, openwisp_controller/subnet_division/tests/test_models.py, tests/openwisp2/sample_subnet_division/tests.py
=> [change] Notify users of background subnet division rule errors #837

openwisp_controller/config/static/config/js/widget.js
I applied the same workaround applied for allowing to use variables in IP address fields.
=> [fix] JS workaround for using mac address variable

openwisp_controller/subnet_division/tests/test_models.py
The [CI build in ansible-openwisp2 was failing](https://github.com/openwisp/ansible-openwisp2/actions/runs/9765910905/job/26960897778#step:7:1275) due to an issue with a test that mocked the logging.Logger.info method. This method is also used by the Celery workers to report task statuses. The additional logs from Celery were affecting the call_args_list index, causing the CI build to fail.
=> [tests] Fixed flaky test_subnets_exhausted

openwisp_controller/subnet_division/base/models.py, openwisp_controller/subnet_division/tests/test_models.py
Fixes #866
-The issue occurs because the code assumes that self.master_subnet and self.master_subnet.subnet are always set, but in this case, they can be None. By adding a check at the beginning of the method, we ensure that a proper validation error is raised when the master subnet is empty or not set.
-The validation error will be caught and displayed in the UI instead of causing a 500 internal server error.
=> [fix] Fixed subnet division rule validation on empty subnet  #866

requirements-test.txt, requirements.txt, setup.py
- Bumped openwisp-users~=1.1.0
- Bumped openwisp-utils[celery]~=1.1.1
- Bumped openwisp-notifications~=1.1.0
- Bumped openwisp-ipam~=1.1.0
- Bumped netjsonconfig~=1.1.0
--------
Removed "publish" from setup.py
=> [deps] Upgraded IPAM, notifications, netjsonconfig, users & utils

CHANGES.rst, openwisp_controller/__init__.py
=> 1.1.0 release

README.rst, openwisp_controller/__init__.py, openwisp_controller/config/base/template.py, openwisp_controller/config/tests/test_template.py
A new regression prevented fixing an invalid template configuration via the UI: the cache invalidation mechanism triggered the evaluation of the configuration which can fail if the configuration is invalid (eg: due to schema updates), hence there was an uncaught ValidationError bubbling up and preventing updates.
This patch fixes this issue.
=> [fix] Allow updating templates with invalid configurations

openwisp_controller/config/tests/test_selenium.py
Added a Selenium test case to replicate the process by creating a device, clicking its anchor tag, pressing ALT+P to open the preview, and pressing ESC to close it.
Fixes #868
Closes #868
- Creates and saves a device configuration.
- Navigate to the device detail page.
- Simulates pressing `Alt + P` to open the preview configuration overlay.
- Verifies that the overlay becomes visible.
- Simulates pressing `Escape` to close the overlay.
- Confirms that the overlay disappears.
=> [tests] Selenium test for Preview configuration with keyboard #868

docs/user/device-config-status.rst, openwisp_controller/config/admin.py, openwisp_controller/config/api/views.py, openwisp_controller/config/static/config/css/device-delete-confirmation.css, openwisp_controller/config/static/config/js/device-delete-confirmation.js, openwisp_controller/config/templates/admin/config/device/delete_confirmation.html, openwisp_controller/config/templates/admin/config/device/delete_selected_confirmation.html, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_api.py, openwisp_controller/config/tests/test_selenium.py, openwisp_controller/tests/test_selenium.py, pyproject.toml
Fixes #949
https://github.com/user-attachments/assets/1fd31e7b-83d4-4bfa-bf02-f5d1ef24bfee
=> [fix] Allowed deleting device with "deactivating" config status #949

.github/workflows/ci.yml, docker-compose.yml, docs/developer/installation.rst, openwisp_controller/config/base/vpn.py, openwisp_controller/config/tests/test_controller.py, openwisp_controller/config/tests/test_template.py, openwisp_controller/connection/base/models.py, openwisp_controller/connection/commands.py, openwisp_controller/connection/migrations/0007_command.py, openwisp_controller/connection/tests/test_models.py, openwisp_controller/connection/tests/test_ssh.py, openwisp_controller/connection/utils.py, openwisp_controller/geo/tests/test_admin_inline.py, openwisp_controller/geo/tests/test_api.py, openwisp_controller/tests/utils.py, requirements-test.txt, requirements.txt, tests/openwisp2/asgi.py, tests/openwisp2/sample_connection/migrations/0001_initial.py, tests/openwisp2/sample_users/migrations/0001_initial.py, tests/openwisp2/settings.py
=> [deps] Upgrade Django 5.x and channels dependencies from openwisp-utils extras

openwisp_controller/config/base/base.py, openwisp_controller/config/base/config.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/validators.py, openwisp_controller/connection/commands.py
The `get_config` method wasn't checking  if `self.name` is defined before using it.
=> [fix] Fixed bug in preview when device has no name

openwisp_controller/config/tests/test_admin.py, tests/openwisp2/sample_config/tests.py
This PR adds tests that seemed to be missing among the sample_config tests
=> [tests] Add missing sample_config admin tests on master

openwisp_controller/geo/tests/test_selenium.py, openwisp_controller/geo/tests/utils.py, requirements.txt
Imported selenium test cases for device admin from `django_loci`. The readonly tests were failing due to user not belonging to the same organization of instances.
Imported selenium test cases for device admin from `django_loci`. 
The readonly tests were failing due to user not belonging to the same organization of instances.
=> [tests] Import django_loci selenium tests, fix failing readonly tests

.github/workflows/ci.yml
Repeat tests withtout the parallel flag because subtests do not get pickled correclty in parallel tests.
=> [ci] Show build errors

openwisp_controller/config/static/config/js/unsaved_changes.js, openwisp_controller/geo/tests/test_selenium.py, openwisp_controller/geo/tests/utils.py
Closes #560.
For readonly mode the field name used to track geometry field is different leading to its json value not being parsed, hence leading to unsaved_changes alert. A small change of addition of the said field in 'jsonValues' of 'unsaved_changes.js' Fixed it.
Also increased the timeout for waiting of success message present for selenium test of device admin to tackle TimeoutException.
=> [fix] Fixed unsaved changes alert for readonly map #560

openwisp_controller/connection/channels/consumers.py, openwisp_controller/connection/tests/pytest.py
Bug:
When multiple connections are made to the websocket command endpoint of the same device (e.g. when multiple browser tabs are open for the same device), the UI does not receive updates from the websocket and keeps showing a loader in the command output field, even when the command has completed execution.
Fix:
The issue was caused by mutating the shared `event` dictionary in the `send_update` method of `CommandConsumer`. Specifically, calling `event.pop('type')` removed the `'type'` key from the event. Since the same event object is dispatched to all consumer instances (one for each websocket connection), removing `'type'` in one instance caused the others to raise:
ValueError: Incoming message has no 'type' attribute
This broke message dispatch …
=> [fix] Fixed live updates for "Send commands"

openwisp_controller/config/tests/test_notifications.py, openwisp_controller/config/utils.py
Bug:
The target_link callable was not returning the correct URL due to changes in openwisp-notifications.
Fix:
Updated the target_link callable for "config_error" notification type and improved test for better E2E testing.
=> [fix] Fixed target URL in "config_error" notification type

openwisp_controller/config/base/config.py, openwisp_controller/config/tests/test_api.py, openwisp_controller/config/tests/test_config.py, openwisp_controller/config/tests/test_vpn.py
=> [fix] Do not allow applying more than 1 templates of same VPN server #832

openwisp_controller/config/tests/test_api.py, openwisp_controller/connection/api/views.py, openwisp_controller/connection/tests/test_api.py
Closes #1040.
Added ordering by creation date (descending) to the Base command view to ensure consistent and expected command ordering and checked all other list apis to ensure recency.
Tests to supported the same added.
=> [fix] Ensure recent items are shown first in the REST API 

openwisp_controller/config/admin.py, openwisp_controller/config/static/config/js/relevant_templates.js, openwisp_controller/config/static/config/js/widget.js, openwisp_controller/config/templates/admin/device_group/change_form.html, openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_selenium.py, openwisp_controller/config/tests/test_views.py, openwisp_controller/config/views.py
Closes #204
Closes #1050
To remove queries generated by sortedm2m, 'formfield_for_manytomany' is overridden such that on page load, we can get templates using 'get_relevant_templates'. 
Added device/group id in 'get_relevant_templates' to identify selected templates. Changes are made in 'relevantTemplates.js' to ensure templates are viewed and changes are saved as per initial behavior.
As now we are fetching  templates via js only, I have done some modifications for the failing test cases.
- for test case `test_device_templates_m2m_queryset` there is a similar selenium test case `test_multiple_organization_templates`
- for test cases `test_configuration_templates_removed` , `test_vpn_clients_deleted`, have added new selenium test cases …
=> [change] Change relevant templates logic to facilitate changing organization +optimizations

.github/workflows/ci.yml
- Add `gosc25-map` and `gsoc25-whois` to get the CI builds
=> [chores] Add gsoc25-map and gsoc25-whois in ci

openwisp_controller/config/tests/test_admin.py, openwisp_controller/config/tests/test_api.py, openwisp_controller/config/tests/test_views.py, openwisp_controller/connection/tests/test_api.py, openwisp_controller/geo/tests/test_api.py, openwisp_controller/pki/tests/test_api.py, tests/openwisp2/settings.py
Set:
```
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
```
to align with the test setup of other openwisp packages.
=> [tests] Sessions now cached in redis

openwisp_controller/connection/static/connection/css/command-inline.css, openwisp_controller/connection/tests/test_selenium.py
=> [fix] Fixed visibility of "Recent Commands" tab on device page

docs/user/rest-api.rst, openwisp_controller/geo/api/serializers.py, openwisp_controller/geo/api/views.py, openwisp_controller/geo/tests/test_api.py, openwisp_controller/geo/utils.py, tests/openwisp2/sample_geo/views.py
Implemented API to return device coordinates for a given location ID.
Fixes #828 
Closes #828 
- Added endpoint `floorplan_coordinates_list` to list coordinates
- Created a new serializer to add this below fields
```
fields = [
"name", 
"mac_address",
"is_deactivated",
"model",
"os",
"floor_name",
"floor",
"image",
"location",
]
```
- Added filter by floor
- Added pagination class
- Added test
=> [feature] Add API endpoint for indoor map coordinates #828

openwisp_controller/config/base/config.py, openwisp_controller/config/tests/test_admin.py
Bug: 
The SortedManyToManyField clears all templates before adding new ones.
This operation emits an `m2m_changed` signal with the `post_clear` action,
which triggers the `Config.enforce_required_templates` receiver to add
required templates back.
Adding required templates emits another `m2m_changed` signal with the
`post_add` action, which executes `Config.manage_vpn_clients` receiver. 
At this point, only required templates exist in the DB, hence we cannot 
decide which VpnClient objects to delete.
Fix:
We don't delete any VpnClient objects when the `m2m_changed` signal 
is sent for the `post_add` action for adding required templates.
The receiver will be called again with the `post_add` action when 
all the templates are added back, including the required ones. 
And then, it will …
=> [fix] Don't delete VpnClients when enforcing required templates

docs/user/estimated-location.rst, docs/user/rest-api.rst, docs/user/whois.rst, openwisp_controller/config/whois/service.py, openwisp_controller/config/whois/test_whois.py, openwisp_controller/geo/admin.py, openwisp_controller/geo/api/filters.py, openwisp_controller/geo/api/serializers.py, openwisp_controller/geo/api/views.py, openwisp_controller/geo/estimated_location/mixins.py, openwisp_controller/geo/estimated_location/test_estimated_location.py
Closes #1028 
Added filters for geographic location in admin via `DeviceLocationFilter` to filter for estimated locations. Since this is a type of location, added 'outdoor' (excluding estimated) and 'indoor' as well.
Added filters for filtering on estimated status via `LocationOrganizationFilter`
Added `is_estimated` field to location lists/objects only if the feature is configured and enabled
=> [enhancement] Estimated Location: Admin and API filters

openwisp_controller/config/base/vpn.py, openwisp_controller/config/tasks.py, openwisp_controller/config/tests/test_vpn.py, openwisp_controller/config/tests/utils.py
Previously, `VpnClient.post_save` re-populated the peer cache immediately. With a large number of peers, this could make uWSGI requests slow or even timeout.
Now, the method only invalidates the peer cache. The cache will be re-populated later by the `trigger_vpn_server_endpoint` task.
Additionally, the `trigger_vpn_server_endpoint` task now has a higher soft time limit (120s) to accommodate generating large configurations for many peers, which could exceed the default
`OpenwispCeleryTask.soft_time_limit`.
Please include any relevant screenshots.
=> [fix] Avoid re-populating peer cache in post_save to prevent slow requests

openwisp_controller/connection/api/views.py, openwisp_controller/connection/tests/test_api.py, openwisp_controller/mixins.py
Added a test to reveal a problem noticed during openwisp 1.1.1 usage.
When a user, who is not a superuser (but with correct permissions), tried to access the details of a device command, an error is triggered:
```
AttributeError: Organization not found, `organization_field` not implemented correctly.
```
This scenario currently seems to be a blind spot in unit tests
Let me know what you think about this...
=> [fix] Fixed DeviceConnection and Command API endpoints for non-superuser

openwisp_controller/pki/api/serializers.py
CI builds were failing as in DRF 3.16+, nullable fields part of unique constraint were getting `default: None` causing Validation errors. Added `default: serializers.empty` to bypass it.
=> [fix] Added "default" kwarg for unique nullable fields
